// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroRealm.Data;


#nullable disable

namespace RetroRealm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240129160031_Technicians")]
    partial class Technicians
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetroRealm.Models.GameModel", b =>
                {
                    b.Property<int>("GameModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameModelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameModelId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameModelId = 1,
                            Code = "CNTPD91",
                            Price = 10m,
                            ReleaseDate = new DateOnly(1981, 6, 15),
                            Title = "Centipede"
                        },
                        new
                        {
                            GameModelId = 2,
                            Code = "ASTRD79",
                            Price = 20m,
                            ReleaseDate = new DateOnly(1979, 11, 17),
                            Title = "Asteroids"
                        },
                        new
                        {
                            GameModelId = 3,
                            Code = "ADVTR80",
                            Price = 20m,
                            ReleaseDate = new DateOnly(1980, 10, 12),
                            Title = "Adventure"
                        });
                });

            modelBuilder.Entity("RetroRealm.Models.TechnicianModel", b =>
                {
                    b.Property<int>("TechnicianModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianModelId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianModelId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianModelId = 1,
                            Email = "alison@retrorealmsoftware.com",
                            Name = "Alison Diaz",
                            Phone = "800-555-0449"
                        },
                        new
                        {
                            TechnicianModelId = 2,
                            Email = "tonyc@retrorealmsoftware.com",
                            Name = "Tony Chef",
                            Phone = "314-123-4567"
                        },
                        new
                        {
                            TechnicianModelId = 3,
                            Email = "poynter@retrorealmsoftware.com",
                            Name = "Trey Poynter",
                            Phone = "573-789-1234"
                        },
                        new
                        {
                            TechnicianModelId = 4,
                            Email = "johnd@retrorealmsoftware.com",
                            Name = "John Doe",
                            Phone = "111-222-3333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
